### ISSUE TITLE
2.0x和3.0x问题

### ISSUE THREAD

**Issue by BryantKawhi** [YangLang116/iFlutter#1]
图片资源的处理能不能针对2.0x和3.0x的做一下兼容

**Comment by YangLang116** [comment]
这个已经计划在下个版本的更新中会带上，预计下个月初

**Comment by BryantKawhi** [comment]
行吧  ，还发现个问题，pubspec.yaml文件如果存在中文或者空行较多，会出现下图的情况
![图片](https://user-images.githubusercontent.com/29621842/155846650-c6a77bbc-a9b7-4d94-9124-d2a8fa83b468.png)

**Comment by YangLang116** [comment]
dimension 兼容需要升级到iFlutter2.0
