### ISSUE TITLE
国际化生出来存在乱码

### ISSUE THREAD

**Issue by BryantKawhi** [YangLang116/iFlutter#12]
![图片](https://user-images.githubusercontent.com/29621842/201129046-8358ed1d-8430-49f4-a1fb-93556114d334.png)
![图片](https://user-images.githubusercontent.com/29621842/201129149-2590583d-083d-4920-97f1-264b8e6d2177.png)

**Comment by YangLang116** [comment]
AndroidStudio Preferences ->  Editor -> File Encoding，在配置界面顶部，Global Encoding\ Project Encoding 设置成UTF-8，试试呢

**Comment by BryantKawhi** [comment]
我设置了，还是乱码哦




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "YangLang116/iFlutter"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年11月11日(星期五) 上午10:43
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [YangLang116/iFlutter] 国际化生出来存在乱码 (Issue #12)





 
AndroidStudio Preferences -&gt;  Editor -&gt; File Encoding，在配置界面顶部，Global Encoding\ Project Encoding 设置成UTF-8，试试呢

**Comment by YangLang116** [comment]
按照上面的方式设置编码以后，记得先删除原始的arb文件，windows编码默认是GBK
