### ISSUE TITLE
convert to local dependency bug

### ISSUE THREAD

**Issue by zlhz** [YangLang116/iFlutter#14]
点击依赖到本地时提示 please run `flutter pub get* first!

**Comment by YangLang116** [comment]
iFlutter会判断项目的根目录，是否存在 .packages文件?  该文件中是否有对应的依赖？，如果没有的话，就需要通过运行flutter pub get 让 flutter生成

**Comment by YangLang116** [comment]
现在命令行执行一下 flutter pub get 看看是否报错

**Comment by zlhz** [comment]
刚试了下，先再terminal输入运行后，还是会提示。我检查了下本地数个项目，都是不存.packages文件是因为新的版本包目录结构变了吗？
flutter版本： Flutter (Channel stable, 3.3.10, on Microsoft Windows [版本 10.0.25300.1000], locale zh-CN)

**Comment by YangLang116** [comment]
flutter3.0 确实存在这个问题，已经提交修复版本2.1.3，等jetbrains市场审核通过，麻烦再更新试试

**Comment by YangLang116** [comment]
市场已经审核通过，麻烦升级iFlutter到2.1.3

**Comment by zlhz** [comment]
功能正常了，感谢作者插件
