### ISSUE TITLE
使用FromJson and ToJson会出现基本数据类型和字符串fromJson和toJson的方法，如图

### ISSUE THREAD

**Issue by a395726103** [YangLang116/iFlutter#17]
![X2{ 75K)AO}CVVEVQD44154](https://github.com/YangLang116/iFlutter/assets/17779490/c2b92df5-72a2-43f6-9060-8f3a1667cea9)

**Comment by a395726103** [comment]
勾选Generate data that cannot be modified  from Json就好了

**Comment by YangLang116** [comment]
在android目录下的local.properties文件中，有flutter.sdk的相关配置吗？例如：
flutter.sdk=/Users/xxx/Library/Android/flutter-env/flutter

如果没有的话，麻烦配置一下，默认这个配置是Flutter自己生成的
