### ISSUE TITLE
idea  2024.2.4 右键没有 iFlutter 选项

### ISSUE THREAD

**Issue by coderleexs** [YangLang116/iFlutter#19]
大神，idea  2024.2.4 右键没有 iFlutter 选项，啥时候更新支持一下 版本 2024.2.x

**Comment by YangLang116** [comment]
麻烦发一下idea的版本详细信息和日志，日志文件在Help -> Show Log in Explore

**Comment by YangLang116** [comment]
好的，idea242兼容性问题，随最近版本修复

**Comment by YangLang116** [comment]
可以更新到4.2.4版本了
