### ISSUE TITLE
fonts问题

### ISSUE THREAD

**Issue by BryantKawhi** [YangLang116/iFlutter#2]
### 1、我按照文档
![图片](https://user-images.githubusercontent.com/29621842/156011602-eb897249-bd9a-4af3-90c7-1d07d3f57372.png)
配置了屏蔽字体的，如下图，
![图片](https://user-images.githubusercontent.com/29621842/156011751-4e05f644-8b0e-46eb-bb49-1d43d6e7c9ff.png)
但是最终生成的代码有这种的。
![图片](https://user-images.githubusercontent.com/29621842/156011873-c3ddcbf5-d72d-4e26-9afe-acf3e2f2a5df.png)
2、不能在pubspec.yaml生成如下图fonts相关的内容，即使我删掉上图的屏蔽.ttf
![图片](https://user-images.githubusercontent.com/29621842/156014244-06ceb4b1-2812-4915-b369-e4d7ff9a5da0.png)

**Comment by YangLang116** [comment]
修改资源感知目录下的资源文件，都会同步到pubspec.yaml的assets节点，配置后缀仅仅控制R文件字段的生成，不会影响assets节点下的内容。iFlutter不会在pubspec.yaml中生成fonts的相关配置，需要手动配置， 图中的字体文件命名和familyname的中不要出现 -， 用 _替换。

**Comment by YangLang116** [comment]
当时考虑font的配置没有asset频繁，为了保证项目成果最大化，就没有做font的配置。现在iFlutter已经趋向稳定，下个版本Font自动注册会跟随pubspec.yaml空白问题一同修复

**Comment by BryantKawhi** [comment]
现在确实挺好用的。但是在图片的我有个需求：图片分类，不同分类下可能会有图片文件名相同，这样生成的R文件就会有问题。我看现在的名字是文件名，这样就有问题

**Comment by YangLang116** [comment]
同一个业务，不同dimension下图片名可以相同，但是不同的业务图片名尽量不一致

**Comment by YangLang116** [comment]
麻烦升级iFlutter到1.2.1，有问题随时反馈

**Comment by YangLang116** [comment]
字体自动注册说明文档：https://github.com/YangLang116/iFlutter/wiki/1%E3%80%81%E8%B5%84%E6%BA%90%E6%96%87%E4%BB%B6%E7%AE%A1%E7%90%86#%E6%B3%A8%E5%86%8C%E5%AD%97%E4%BD%93
