### ISSUE TITLE
有个小问题

### ISSUE THREAD

**Issue by Unicorn254** [YangLang116/iFlutter#5]
首先非常感谢作则提供便利的插件，但是我在使用过程中发现，点击generate res 后会清空我res文件夹下面已存在的文件。 目前使用的版本是1.3.5

**Comment by YangLang116** [comment]
generate res 只是重新生成_res.dart相关的文件，并不会删除文件。但如果遇到这个问题，麻烦确认一下：

1、在res目录右键，选择 Reload From Disk 看看丢失文件是否恢复
2、IDEA右下角是否有 红色感叹号，如果有麻烦点进去看一下，是否存在包名为 com.xtu.plugin...的堆栈日志

**Comment by YangLang116** [comment]
3、是否丢失文件为 i_font_res.dart

**Comment by Unicorn254** [comment]
> generate res 只是重新生成_res.dart相关的文件，并不会删除文件。但如果遇到这个问题，麻烦确认一下：
> 
> 1、在res目录右键，选择 Reload From Disk 看看丢失文件是否恢复 2、IDEA右下角是否有 红色感叹号，如果有麻烦点进去看一下，是否存在包名为 com.xtu.plugin...的堆栈日志

1.Reload From Disk 后文件不能恢复
2.并未有红色感叹号
3.在res我放了一些 颜色 、静态变量、样式等一些文件，generate res之后这些文件全部会丢失，只会存在i_font_res.dart

**Comment by YangLang116** [comment]
res目录由iFlutter进行管理，不要在该目录下放置业务相关的代码。

**Comment by YangLang116** [comment]
在一个空的项目中添加一张图片资源，iFlutter会自动生成_res.dart文件，如果把这张图片删除，iFlutter会同步删除_res.dart文件。考虑类似这样的情况，iFlutter会自动删除res目录下那些对iFlutter来说无用的文件。

**Comment by YangLang116** [comment]
如果出现 i_font_res.dart 文件被误删的情况，麻烦后面升级到 v1.3.6版本，该版本已经在审核中了！

感谢使用iFlutter插件

**Comment by Unicorn254** [comment]
> res目录由iFlutter进行管理，不要在该目录下放置业务相关的代码。

还没开始用大大的插件的时候就已经创建了res文件夹了，这就有点尴尬 hhh

**Comment by YangLang116** [comment]
￣□￣｜｜，这确实不好意思，是前期考虑不周，不应该取一个这么通用的名字
