### ISSUE TITLE
json 2 Dart的问题

### ISSUE THREAD

**Issue by BryantKawhi** [YangLang116/iFlutter#6]
为啥我生成的dart  把json字段的驼峰全转成了小写
![image](https://user-images.githubusercontent.com/29621842/170408422-66b7f1fd-def6-4eec-97f8-e5664d3913a8.png)

**Comment by YangLang116** [comment]
能贴一下json字符 以及 iflutter版本号么

**Comment by BryantKawhi** [comment]
> 能贴一下json字符 以及 iflutter版本号么

![image](https://user-images.githubusercontent.com/29621842/170408920-b59142dc-07d2-4be1-870d-38328c951f26.png)
 {
		"markerId": 12,
		"markerCode": "6096894054000001",
		"boxCode": "GYS13XT001",
		"qaStatus": 10,
		"supplierName": "测试",
		"supplierAddr": "余家湾"
	}

**Comment by YangLang116** [comment]
iflutter通过字符  '-',  '_' 来区分单词大小写，比如 marker_code（marker-code），就会转成markerCode，否则都会按照小写处理

**Comment by YangLang116** [comment]
为了兼容情况，在v2.0.3版本修复，感谢反馈

**Comment by YangLang116** [comment]
v2.0.3版本已经审核通过，麻烦更新已解决这一问题

**Comment by BryantKawhi** [comment]
好的&nbsp;&nbsp; 好的&nbsp;&nbsp; 谢谢大佬




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "YangLang116/iFlutter"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年5月26日(星期四) 下午4:26
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [YangLang116/iFlutter] json 2 Dart的问题 (Issue #6)





 
v2.0.3版本已经审核通过，麻烦更新已解决这一问题
